-- SQL Schema for Training and Placement Department Management System
-- Compatibility: Oracle SQL / Generic SQL

-- 1. USERS TABLE (For Authentication and Roles)
CREATE TABLE Users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) CHECK (role IN ('STUDENT', 'TPO', 'COMPANY')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. STUDENTS TABLE
CREATE TABLE Students (
    student_id INT PRIMARY KEY,
    user_id INT UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    department VARCHAR(50) NOT NULL,
    graduation_year INT NOT NULL,
    cgpa DECIMAL(3, 2) CHECK (cgpa >= 0.00 AND cgpa <= 10.00),
    resume_url VARCHAR(255), -- Link to uploaded resume
    is_placed NUMBER(1) DEFAULT 0 CHECK (is_placed IN (0, 1)),
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- 3. COMPANIES TABLE
CREATE TABLE Companies (
    company_id INT PRIMARY KEY,
    user_id INT UNIQUE NOT NULL,
    company_name VARCHAR(100) NOT NULL,
    industry VARCHAR(50),
    website_url VARCHAR(255),
    contact_email VARCHAR(100) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- 4. PLACEMENT DRIVES TABLE (Job Postings/Drives scheduled by companies)
CREATE TABLE Placement_Drives (
    drive_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    job_title VARCHAR(100) NOT NULL,
    job_description CLOB,
    package_offered DECIMAL(10, 2), -- Package in LPA or desired currency
    minimum_cgpa DECIMAL(3, 2) DEFAULT 0.00,
    drive_date DATE NOT NULL,
    status VARCHAR(20) DEFAULT ('ONGOING') CHECK (status IN ('UPCOMING', 'ONGOING', 'COMPLETED')),
    FOREIGN KEY (company_id) REFERENCES Companies(company_id) ON DELETE CASCADE
);

-- 5. APPLICATIONS TABLE (Students applying for drives)
CREATE TABLE Applications (
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    drive_id INT NOT NULL,
    application_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT ('APPLIED') CHECK (status IN ('APPLIED', 'INTERVIEWING', 'OFFERED', 'REJECTED')),
    FOREIGN KEY (student_id) REFERENCES Students(student_id) ON DELETE CASCADE,
    FOREIGN KEY (drive_id) REFERENCES Placement_Drives(drive_id) ON DELETE CASCADE,
    UNIQUE (student_id, drive_id) -- A student can only apply once per drive
);
