

-- ---------------------------------------------------------
-- 1. INSERT (Create Operations)
-- ---------------------------------------------------------

-- Scenario A: A new company is added to the system via "Add Company" button
INSERT INTO Users (username, password_hash, role) 
VALUES ('hr@uber.com', 'hashed_pass_456', 'COMPANY');

-- We retrieve the autogenerated user_id (assume it is 501 for this example)
INSERT INTO Companies (company_id, user_id, company_name, industry, website_url, contact_email) 
VALUES (101, 501, 'Uber', 'Ride-sharing', 'https://uber.com', 'careers@uber.com');

-- Scenario B: HR schedules a new placement drive via "Schedule Drive" button
INSERT INTO Placement_Drives (company_id, job_title, job_description, package_offered, minimum_cgpa, drive_date, status)
VALUES (
    101, 
    'Backend Engineer', 
    'Looking for developers with strong SQL knowledge.', 
    18.50, 
    7.50, 
    TO_DATE('2026-11-20', 'YYYY-MM-DD'), 
    'UPCOMING'
);

-- Scenario C: Student "John Doe" applies for this new drive
INSERT INTO Applications (student_id, drive_id, application_date, status)
VALUES (1, 10, CURRENT_TIMESTAMP, 'APPLIED');


-- ---------------------------------------------------------
-- 2. UPDATE (Modify Operations)
-- ---------------------------------------------------------

-- Scenario A: A student progresses through an interview round (TPO dashboard action)
UPDATE Applications
SET status = 'INTERVIEWING'
WHERE student_id = 1 AND drive_id = 10;

-- Scenario B: The placement drive is officially over
UPDATE Placement_Drives
SET status = 'COMPLETED'
WHERE drive_date < CURRENT_DATE AND status = 'ONGOING';


-- ---------------------------------------------------------
-- 3. DELETE (Remove Operations)
-- ---------------------------------------------------------

-- Scenario A: A company withdraws their job posting
DELETE FROM Placement_Drives
WHERE drive_id = 10 AND status = 'UPCOMING';

-- Note: Because we defined ON DELETE CASCADE in the schema.sql earlier, 
--       deleting the drive will automatically delete all related student applications to that drive!


-- ---------------------------------------------------------
-- 4. COMPLEX SELECTS (Retrieval Operations for Dashboards)
-- ---------------------------------------------------------

-- Query 1: The "Recent Placements" Table in the Admin Dashboard
-- This query joins Students, Applications, and Companies to generate the rows seen in the React UI
SELECT 
    s.first_name || ' ' || s.last_name AS Student_Name,
    s.department AS Department,
    c.company_name AS Company_Offer,
    d.package_offered AS Package,
    a.status AS Offer_Status
FROM Applications a
JOIN Students s ON a.student_id = s.student_id
JOIN Placement_Drives d ON a.drive_id = d.drive_id
JOIN Companies c ON d.company_id = c.company_id
WHERE a.status IN ('OFFERED', 'ACCEPTED')
ORDER BY a.application_date DESC
FETCH FIRST 10 ROWS ONLY;

-- Query 2: KPI Metrics ("Total Placed Students" widget)
SELECT COUNT(*) AS total_placed_students
FROM Students
WHERE is_placed = 1;

-- Query 3: Student Portal ("Active Applications")
SELECT 
    c.company_name, 
    d.job_title, 
    a.status, 
    a.application_date
FROM Applications a
JOIN Placement_Drives d ON a.drive_id = d.drive_id
JOIN Companies c ON d.company_id = c.company_id
WHERE a.student_id = 1001 -- Dynamic ID based on login
ORDER BY a.application_date DESC;
